# Generated by Django 4.2.20 on 2025-05-31 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gcs_blob_name",
                    models.CharField(
                        help_text="Name of the file in Google Cloud Storage",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Landmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detected_landmark_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "formatted_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("street_number", models.SmallIntegerField(blank=True, null=True)),
                ("route", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "neighborhood",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sublocality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "analysis_timestamp",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When landmark analysis was last updated/completed",
                    ),
                ),
                (
                    "photo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landmark_data",
                        to="photouploadapi.photo",
                    ),
                ),
            ],
        ),
    ]
