# Generated by Django 4.2.20 on 2025-05-06 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("logged_in", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Landmark",
            fields=[
                ("landmark_id", models.AutoField(primary_key=True, serialize=False)),
                ("photo_id", models.ImageField(upload_to="landmark_photos/")),
                ("processed", models.BooleanField(default=False)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                (
                    "formatted_address",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("street_number", models.SmallIntegerField(blank=True, null=True)),
                ("route", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "neighborhood",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("sublocality", models.CharField(blank=True, max_length=30, null=True)),
                ("state", models.CharField(blank=True, max_length=30, null=True)),
                ("district", models.CharField(blank=True, max_length=30, null=True)),
                ("country", models.CharField(blank=True, max_length=30, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="photouploadapi.user",
                    ),
                ),
            ],
        ),
    ]
